<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CentersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = DB::table('cities')->pluck('id', 'name')->toArray();

        $centers = [
            // RÉGION DU CENTRE - YAOUNDÉ
            [
                'name' => 'SIÈGE INTELLIGENTSIA',
                'location' => 'Montée CRADAT, 3ème étage immeuble Intelligentsia',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PRIMAIRE LE TREMPLIN',
                'location' => 'Face Collège FX Vogt',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PRIMAIRE LA RETRAITE',
                'location' => 'Warda derrière le collège de la Retraite',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COMPLEXE SCOLAIRE AMASIA',
                'location' => 'Derrière SNEC Ekounou',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COMPLEXE SCOLAIRE L\'ESPÉRANCE',
                'location' => 'COPES, mobile Omnisports',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'GROUPE SCOLAIRE BILINGUE LES CHAMPIONS',
                'location' => 'Borne fontaine Emana',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COMPLEXE SCOLAIRE YONA',
                'location' => 'Carrefour Nkolbisson',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE BILINGUE AFRICAINE LES ÉTOILES',
                'location' => 'BASS, face TOTAL Jouvence',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE CATHOLIQUE SAINT PIERRE APÔTRE',
                'location' => 'Messamendongo, derrière le commissariat',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COLLÈGE BERCEAU DES ANGES',
                'location' => 'Neptune Simbock',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'INSTITUT POLYVALENT BILINGUE TCHEUTCHOUA',
                'location' => '10e arrêt Nkoabang',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COLLÈGE BISTA',
                'location' => 'Nkolbisson, carrefour Onana',
                'city_id' => $cities['YAOUNDÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DU LITTORAL - DOUALA
            [
                'name' => 'COLLÈGE POLYVALENT SUZANNA',
                'location' => 'À 50 m face MTN Dakar',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'COLLÈGE POLYVALENT NANFAH',
                'location' => 'Face parcours Vita Bonamoussadi',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ISECMA',
                'location' => '50 m du carrefour lycée de la cité des palmiers',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'SOFT EDUCATION',
                'location' => 'Juste après Total NKOLBONG à Yassa',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PRIMAIRE LA SOURCE',
                'location' => 'Derrière le collège MOHOUA à l\'entrée carrefour Grand moulin à Deïdo',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PRIMAIRE PETIT MONDE',
                'location' => 'Quartier Grand moulin à Deïdo',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PUBLIQUE DE BONABERI',
                'location' => 'Bonaberi',
                'city_id' => $cities['DOUALA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DU LITTORAL - NKONGSAMBA
            [
                'name' => 'ÉCOLE PRIMAIRE LAÏQUE UNITE',
                'location' => 'ILE',
                'city_id' => $cities['NKONGSAMBA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DE L'OUEST - BAFOUSSAM
            [
                'name' => 'SIEGE INTELLIGENTSIA BAFOUSSAM',
                'location' => 'Au-dessus de Pharmacie Madelon',
                'city_id' => $cities['BAFOUSSAM'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PUBLIQUE DU CENTRE III-A DE BAFOUSSAM',
                'location' => 'Juste avant Lycée Bilingue de Bafoussam',
                'city_id' => $cities['BAFOUSSAM'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
            [
                'name' => 'ÉCOLE PRIMAIRE SAINT JOSEPH',
                'location' => 'Face Cathédrale',
                'city_id' => $cities['BAFOUSSAM'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DE L'OUEST - BANGANGTÉ
            [
                'name' => 'ÉCOLE PRIMAIRE D\'APPLICATION DE BANGANGTÉ',
                'location' => 'Bangangté',
                'city_id' => $cities['BANGANGTÉ'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DE L'OUEST - DSCHANG
            [
                'name' => 'ÉCOLE PRIMAIRE DU PLATEAU',
                'location' => 'Face stade CENAJES de Dschang',
                'city_id' => $cities['DSCHANG'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DU SUD - EBOLOWA
            [
                'name' => 'ÉCOLE PUBLIQUE SAMBA',
                'location' => 'Ancien ENIEG d\'Ebolowa',
                'city_id' => $cities['EBOLOWA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DE L'EST - BERTOUA
            [
                'name' => 'COLLÈGE ADVENTISTE DE BERTOUA',
                'location' => 'Bertoua',
                'city_id' => $cities['BERTOUA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DU GRAND NORD - GAROUA
            [
                'name' => 'COLLÈGE MODERNE DE LA BENOUÉ',
                'location' => 'Garoua',
                'city_id' => $cities['GAROUA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],

            // RÉGION DU GRAND NORD - MAROUA
            [
                'name' => 'GROUPE SCOLAIRE BILINGUE BEN FATIMA',
                'location' => 'À côté de l\'école publique de Kaigama',
                'city_id' => $cities['MAROUA'] ?? null,
                'nb_students' => 0,
                'director_id' => null,
                'head_id' => null,
                'logistics_director_id' => null,
                'finance_director_id' => null,
                'academic_manager_id' => null,
                'staff_ids' => null,
                'is_active' => true,
            ],
        ];

        DB::table('centers')->insert($centers);
    }
}